In [1]:
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, lit

C:\Users\HP\anaconda3\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\HP\anaconda3\lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
C:\Users\HP\anaconda3\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"

In [2]:
spark = SparkSession.builder.appName("df_to_RDD").getOrCreate()

In [3]:
df = spark.read.options(header = True, inferSchema = True).csv("StudentData.csv")
df.show()

+---+------+----------------+------+------+-----+--------------------+
|age|gender|            name|course|  roll|marks|               email|
+---+------+----------------+------+------+-----+--------------------+
| 28|Female| Hubert Oliveras|    DB|  2984|   59|Annika Hoffman_Na...|
| 29|Female|Toshiko Hillyard| Cloud| 12899|   62|Margene Moores_Ma...|
| 28|  Male|  Celeste Lollis|    PF| 21267|   45|Jeannetta Golden_...|
| 29|Female|    Elenore Choy|    DB| 32877|   29|Billi Clore_Mitzi...|
| 28|  Male|  Sheryll Towler|   DSA| 41487|   41|Claude Panos_Judi...|
| 28|  Male|  Margene Moores|   MVC| 52771|   32|Toshiko Hillyard_...|
| 28|  Male|     Neda Briski|   OOP| 61973|   69|Alberta Freund_El...|
| 28|Female|    Claude Panos| Cloud| 72409|   85|Sheryll Towler_Al...|
| 28|  Male|  Celeste Lollis|   MVC| 81492|   64|Nicole Harwood_Cl...|
| 29|  Male|  Cordie Harnois|   OOP| 92882|   51|Judie Chipps_Clem...|
| 29|Female|       Kena Wild|   DSA|102285|   35|Dustin Feagins_Ma...|
| 29|  Male| Ernest Rossbach|    DB|111449|   53|Maybell Duguay_Ab...|
| 28|Female|  Latia Vanhoose|    DB|122502|   27|Latia Vanhoose_Mi...|
| 29|Female|  Latia Vanhoose|   MVC|132110|   55|Eda Neathery_Nico...|
| 29|  Male|     Neda Briski|    PF|141770|   42|Margene Moores_Mi...|
| 29|Female|  Latia Vanhoose|    DB|152159|   27|Claude Panos_Sant...|
| 29|  Male|  Loris Crossett|   MVC|161771|   36|Mitzi Seldon_Jenn...|
| 29|  Male|  Annika Hoffman|   OOP|171660|   22|Taryn Brownlee_Mi...|
| 29|  Male|   Santa Kerfien|    PF|182129|   56|Judie Chipps_Tary...|
| 28|Female|Mickey Cortright|    DB|192537|   62|Ernest Rossbach_M...|
+---+------+----------------+------+------+-----+--------------------+
only showing top 20 rows

In [4]:
type(df)

pyspark.sql.dataframe.DataFrame

In [5]:
rdd = df.rdd

In [6]:
type(rdd)

pyspark.rdd.RDD

In [7]:
rdd.collect()

[Row(age=28, gender='Female', name='Hubert Oliveras', course='DB', roll=2984, marks=59, email='Annika Hoffman_Naoma Fritts@OOP.com'),
 Row(age=29, gender='Female', name='Toshiko Hillyard', course='Cloud', roll=12899, marks=62, email='Margene Moores_Marylee Capasso@DB.com'),
 Row(age=28, gender='Male', name='Celeste Lollis', course='PF', roll=21267, marks=45, email='Jeannetta Golden_Jenna Montague@DSA.com'),
 Row(age=29, gender='Female', name='Elenore Choy', course='DB', roll=32877, marks=29, email='Billi Clore_Mitzi Seldon@DB.com'),
 Row(age=28, gender='Male', name='Sheryll Towler', course='DSA', roll=41487, marks=41, email='Claude Panos_Judie Chipps@OOP.com'),
 Row(age=28, gender='Male', name='Margene Moores', course='MVC', roll=52771, marks=32, email='Toshiko Hillyard_Clementina Menke@MVC.com'),
 Row(age=28, gender='Male', name='Neda Briski', course='OOP', roll=61973, marks=69, email='Alberta Freund_Elenore Choy@DB.com'),
 Row(age=28, gender='Female', name='Claude Panos', course='Cloud', roll=72409, marks=85, email='Sheryll Towler_Alberta Freund@Cloud.com'),
 Row(age=28, gender='Male', name='Celeste Lollis', course='MVC', roll=81492, marks=64, email='Nicole Harwood_Claude Panos@MVC.com'),
 Row(age=29, gender='Male', name='Cordie Harnois', course='OOP', roll=92882, marks=51, email='Judie Chipps_Clementina Menke@MVC.com'),
 Row(age=29, gender='Female', name='Kena Wild', course='DSA', roll=102285, marks=35, email='Dustin Feagins_Margene Moores@OOP.com'),
 Row(age=29, gender='Male', name='Ernest Rossbach', course='DB', roll=111449, marks=53, email='Maybell Duguay_Abram Nagao@OOP.com'),
 Row(age=28, gender='Female', name='Latia Vanhoose', course='DB', roll=122502, marks=27, email='Latia Vanhoose_Mitzi Seldon@OOP.com'),
 Row(age=29, gender='Female', name='Latia Vanhoose', course='MVC', roll=132110, marks=55, email='Eda Neathery_Nicole Harwood@Cloud.com'),
 Row(age=29, gender='Male', name='Neda Briski', course='PF', roll=141770, marks=42, email='Margene Moores_Michelle Ruggiero@MVC.com'),
 Row(age=29, gender='Female', name='Latia Vanhoose', course='DB', roll=152159, marks=27, email='Claude Panos_Santa Kerfien@DB.com'),
 Row(age=29, gender='Male', name='Loris Crossett', course='MVC', roll=161771, marks=36, email='Mitzi Seldon_Jenna Montague@MVC.com'),
 Row(age=29, gender='Male', name='Annika Hoffman', course='OOP', roll=171660, marks=22, email='Taryn Brownlee_Mitzi Seldon@MVC.com'),
 Row(age=29, gender='Male', name='Santa Kerfien', course='PF', roll=182129, marks=56, email='Judie Chipps_Taryn Brownlee@Cloud.com'),
 Row(age=28, gender='Female', name='Mickey Cortright', course='DB', roll=192537, marks=62, email='Ernest Rossbach_Marylee Capasso@Cloud.com'),
 Row(age=29, gender='Female', name='Loris Crossett', course='PF', roll=201487, marks=96, email='Elenore Choy_Latia Vanhoose@Cloud.com'),
 Row(age=29, gender='Female', name='Niki Klimek', course='PF', roll=211508, marks=23, email='Cordie Harnois_Judie Chipps@PF.com'),
 Row(age=28, gender='Female', name='Kena Wild', course='Cloud', roll=221750, marks=60, email='Mitzi Seldon_Jenna Montague@DSA.com'),
 Row(age=28, gender='Female', name='Jc Andrepont', course='DSA', roll=232060, marks=58, email='Billi Clore_Abram Nagao@MVC.com'),
 Row(age=29, gender='Female', name='Anna Santos', course='Cloud', roll=242254, marks=68, email='Jc Andrepont_Hubert Oliveras@Cloud.com'),
 Row(age=28, gender='Female', name='Alberta Freund', course='OOP', roll=251805, marks=83, email='Annika Hoffman_Sheryll Towler@MVC.com'),
 Row(age=28, gender='Female', name='Maybell Duguay', course='Cloud', roll=261439, marks=20, email='Nicole Harwood_Judie Chipps@DB.com'),
 Row(age=29, gender='Female', name='Paris Hutton', course='DSA', roll=271472, marks=99, email='Sheryll Towler_Alberta Freund@DSA.com'),
 Row(age=29, gender='Female', name='Cheri Kenney', course='Cloud', roll=281408, marks=43, email='Annika Hoffman_Melani Engberg@Cloud.com'),
 Row(age=28, gender='Female', name='Dustin Feagins', course='DSA', roll=291984, marks=82, email='Abram Nagao_Kena Wild@Cloud.com'),
 Row(age=29, gender='Female', name='Claude Panos', course='Cloud', roll=302130, marks=59, email='Sheryll Towler_Leontine Phillips@PF.com'),
 Row(age=28, gender='Female', name='Anna Santos', course='DB', roll=311589, marks=79, email='Celeste Lollis_Mickey Cortright@DSA.com'),
 Row(age=28, gender='Female', name='Cheri Kenney', course='MVC', roll=321816, marks=24, email='Kena Wild_Michelle Ruggiero@DB.com'),
 Row(age=28, gender='Female', name='Loris Crossett', course='PF', roll=332739, marks=62, email='Michelle Ruggiero_Clementina Menke@DB.com'),
 Row(age=28, gender='Female', name='Mickey Cortright', course='DSA', roll=342003, marks=44, email='Mitzi Seldon_Jeannetta Golden@PF.com'),
 Row(age=28, gender='Male', name='Hubert Oliveras', course='OOP', roll=351719, marks=63, email='Lawanda Wohlwend_Abram Nagao@MVC.com'),
 Row(age=28, gender='Male', name='Sebrina Maresca', course='PF', roll=361316, marks=62, email='Nicole Harwood_Latia Vanhoose@DB.com'),
 Row(age=29, gender='Male', name='Jalisa Swenson', course='PF', roll=372873, marks=45, email='Ernest Rossbach_Toshiko Hillyard@DB.com'),
 Row(age=28, gender='Male', name='Kizzy Brenner', course='DB', roll=381712, marks=36, email='Paris Hutton_Kena Wild@MVC.com'),
 Row(age=28, gender='Male', name='Toshiko Hillyard', course='DB', roll=392218, marks=47, email='Leontine Phillips_Billi Clore@MVC.com'),
 Row(age=28, gender='Female', name='Kizzy Brenner', course='Cloud', roll=402409, marks=27, email='Ernest Rossbach_Gonzalo Ferebee@OOP.com'),
 Row(age=29, gender='Female', name='Anna Santos', course='DSA', roll=411479, marks=42, email='Kena Wild_Mitzi Seldon@DB.com'),
 Row(age=28, gender='Male', name='Elenore Choy', course='PF', roll=422704, marks=66, email='Marylee Capasso_Nicole Harwood@MVC.com'),
 Row(age=28, gender='Female', name='Jalisa Swenson', course='OOP', roll=431352, marks=25, email='Gonzalo Ferebee_Judie Chipps@DB.com'),
 Row(age=29, gender='Female', name='Somer Stoecker', course='Cloud', roll=442028, marks=34, email='Taryn Brownlee_Taryn Brownlee@MVC.com'),
 Row(age=28, gender='Female', name='Maybell Duguay', course='DSA', roll=452141, marks=29, email='Leontine Phillips_Elenore Choy@Cloud.com'),
 Row(age=28, gender='Male', name='Dustin Feagins', course='PF', roll=461839, marks=51, email='Neda Briski_Elenore Choy@Cloud.com'),
 Row(age=29, gender='Male', name='Annika Hoffman', course='OOP', roll=472550, marks=35, email='Mitzi Seldon_Abram Nagao@DSA.com'),
 Row(age=29, gender='Male', name='Paris Hutton', course='DB', roll=481229, marks=57, email='Clementina Menke_Paris Hutton@MVC.com'),
 Row(age=29, gender='Female', name='Paris Hutton', course='DSA', roll=492159, marks=60, email='Nicole Harwood_Marylee Capasso@OOP.com'),
 Row(age=29, gender='Female', name='Jenna Montague', course='MVC', roll=502585, marks=43, email='Hubert Oliveras_Jc Andrepont@DSA.com'),
 Row(age=29, gender='Male', name='Billi Clore', course='Cloud', roll=512047, marks=76, email='Taryn Brownlee_Judie Chipps@DSA.com'),
 Row(age=29, gender='Male', name='Toshiko Hillyard', course='OOP', roll=521221, marks=77, email='Hubert Oliveras_Latia Vanhoose@MVC.com'),
 Row(age=28, gender='Male', name='Margene Moores', course='PF', roll=531530, marks=53, email='Cheri Kenney_Melani Engberg@OOP.com'),
 Row(age=29, gender='Female', name='Claude Panos', course='OOP', roll=542821, marks=28, email='Hubert Oliveras_Priscila Tavernier@PF.com'),
 Row(age=28, gender='Female', name='Mickey Cortright', course='DB', roll=551389, marks=43, email='Tijuana Kropf_Jenna Montague@DB.com'),
 Row(age=29, gender='Male', name='Celeste Lollis', course='DSA', roll=562065, marks=85, email='Jc Andrepont_Melani Engberg@OOP.com'),
 Row(age=28, gender='Female', name='Tijuana Kropf', course='PF', roll=571047, marks=41, email='Loris Crossett_Sebrina Maresca@PF.com'),
 Row(age=28, gender='Male', name='Marylee Capasso', course='OOP', roll=581756, marks=52, email='Jeannetta Golden_Loris Crossett@MVC.com'),
 Row(age=29, gender='Male', name='Maybell Duguay', course='DSA', roll=592061, marks=83, email='Eda Neathery_Jenna Montague@Cloud.com'),
 Row(age=28, gender='Female', name='Leontine Phillips', course='DB', roll=602404, marks=48, email='Neda Briski_Cheri Kenney@PF.com'),
 Row(age=28, gender='Female', name='Somer Stoecker', course='Cloud', roll=612490, marks=82, email='Sebrina Maresca_Gonzalo Ferebee@DSA.com'),
 Row(age=28, gender='Male', name='Mitzi Seldon', course='DSA', roll=622981, marks=45, email='Lawanda Wohlwend_Loris Crossett@DSA.com'),
 Row(age=29, gender='Female', name='Judie Chipps', course='Cloud', roll=632793, marks=75, email='Tijuana Kropf_Elenore Choy@PF.com'),
 Row(age=28, gender='Male', name='Priscila Tavernier', course='PF', roll=642594, marks=27, email='Marylee Capasso_Claude Panos@DSA.com'),
 Row(age=29, gender='Male', name='Tamera Blakley', course='MVC', roll=651649, marks=92, email='Latia Vanhoose_Toshiko Hillyard@MVC.com'),
 Row(age=28, gender='Male', name='Sheryll Towler', course='MVC', roll=661079, marks=89, email='Tijuana Kropf_Mickey Cortright@DB.com'),
 Row(age=29, gender='Male', name='Hubert Oliveras', course='MVC', roll=672451, marks=28, email='Annika Hoffman_Mickey Cortright@DSA.com'),
 Row(age=29, gender='Male', name='Sheryll Towler', course='PF', roll=682533, marks=42, email='Billi Clore_Anna Santos@PF.com'),
 Row(age=28, gender='Female', name='Jenna Montague', course='DSA', roll=691564, marks=26, email='Mitzi Seldon_Sebrina Maresca@Cloud.com'),
 Row(age=29, gender='Male', name='Maybell Duguay', course='PF', roll=701486, marks=99, email='Clementina Menke_Latia Vanhoose@Cloud.com'),
 Row(age=29, gender='Male', name='Jenna Montague', course='MVC', roll=711153, marks=45, email='Marylee Capasso_Hubert Oliveras@DB.com'),
 Row(age=28, gender='Male', name='Annika Hoffman', course='Cloud', roll=722193, marks=55, email='Taryn Brownlee_Elenore Choy@DB.com'),
 Row(age=28, gender='Female', name='Celeste Lollis', course='DSA', roll=731879, marks=76, email='Hubert Oliveras_Gonzalo Ferebee@DSA.com'),
 Row(age=29, gender='Male', name='Jeannetta Golden', course='MVC', roll=741875, marks=57, email='Sheryll Towler_Cheri Kenney@DSA.com'),
 Row(age=29, gender='Male', name='Paris Hutton', course='MVC', roll=752504, marks=22, email='Elenore Choy_Elenore Choy@DB.com'),
 Row(age=29, gender='Female', name='Margene Moores', course='MVC', roll=761843, marks=48, email='Ernest Rossbach_Mickey Cortright@DSA.com'),
 Row(age=28, gender='Female', name='Hubert Oliveras', course='DB', roll=771081, marks=79, email='Kizzy Brenner_Dustin Feagins@MVC.com'),
 Row(age=28, gender='Male', name='Alberta Freund', course='PF', roll=781061, marks=75, email='Leontine Phillips_Bonita Higuera@PF.com'),
 Row(age=29, gender='Female', name='Billi Clore', course='OOP', roll=791519, marks=93, email='Elenore Choy_Jalisa Swenson@MVC.com'),
 Row(age=28, gender='Female', name='Billi Clore', course='Cloud', roll=801693, marks=38, email='Niki Klimek_Kizzy Brenner@DB.com'),
 Row(age=29, gender='Female', name='Elenore Choy', course='DB', roll=811824, marks=55, email='Maybell Duguay_Melani Engberg@DB.com'),
 Row(age=28, gender='Male', name='Anna Santos', course='OOP', roll=822396, marks=47, email='Leontine Phillips_Gonzalo Ferebee@Cloud.com'),
 Row(age=28, gender='Male', name='Sheryll Towler', course='DSA', roll=831562, marks=59, email='Kena Wild_Gonzalo Ferebee@Cloud.com'),
 Row(age=29, gender='Male', name='Neda Briski', course='PF', roll=842515, marks=68, email='Neda Briski_Hubert Oliveras@OOP.com'),
 Row(age=28, gender='Female', name='Santa Kerfien', course='Cloud', roll=851620, marks=34, email='Melani Engberg_Sheryll Towler@PF.com'),
 Row(age=29, gender='Female', name='Taryn Brownlee', course='MVC', roll=861849, marks=39, email='Billi Clore_Toshiko Hillyard@MVC.com'),
 Row(age=28, gender='Female', name='Sheryll Towler', course='DSA', roll=871967, marks=64, email='Michelle Ruggiero_Billi Clore@Cloud.com'),
 Row(age=29, gender='Male', name='Clementina Menke', course='DB', roll=882200, marks=76, email='Michelle Ruggiero_Jenna Montague@MVC.com'),
 Row(age=28, gender='Male', name='Margene Moores', course='DSA', roll=892010, marks=93, email='Anna Santos_Naoma Fritts@DSA.com'),
 Row(age=28, gender='Female', name='Somer Stoecker', course='DSA', roll=901958, marks=64, email='Kizzy Brenner_Jc Andrepont@DB.com'),
 Row(age=29, gender='Male', name='Loris Crossett', course='PF', roll=911593, marks=46, email='Gonzalo Ferebee_Mitzi Seldon@PF.com'),
 Row(age=29, gender='Female', name='Sebrina Maresca', course='DB', roll=922210, marks=54, email='Toshiko Hillyard_Santa Kerfien@MVC.com'),
 Row(age=29, gender='Male', name='Naoma Fritts', course='DB', roll=931295, marks=79, email='Hubert Oliveras_Sheryll Towler@DSA.com'),
 Row(age=28, gender='Female', name='Santa Kerfien', course='MVC', roll=941783, marks=94, email='Paris Hutton_Naoma Fritts@DB.com'),
 Row(age=28, gender='Female', name='Lawanda Wohlwend', course='DSA', roll=951686, marks=60, email='Loris Crossett_Nicole Harwood@DSA.com'),
 Row(age=29, gender='Male', name='Abram Nagao', course='MVC', roll=962235, marks=32, email='Jenna Montague_Gonzalo Ferebee@DSA.com'),
 Row(age=28, gender='Female', name='Jc Andrepont', course='PF', roll=972733, marks=20, email='Eda Neathery_Eda Neathery@MVC.com'),
 Row(age=29, gender='Male', name='Niki Klimek', course='PF', roll=982443, marks=94, email='Santa Kerfien_Kizzy Brenner@DB.com'),
 Row(age=28, gender='Female', name='Marylee Capasso', course='OOP', roll=991770, marks=86, email='Margene Moores_Clementina Menke@DB.com'),
 Row(age=28, gender='Male', name='Jenna Montague', course='DSA', roll=1002103, marks=36, email='Melani Engberg_Hubert Oliveras@PF.com'),
 Row(age=29, gender='Female', name='Eda Neathery', course='Cloud', roll=1011971, marks=91, email='Margene Moores_Elenore Choy@MVC.com'),
 Row(age=29, gender='Male', name='Michelle Ruggiero', course='DSA', roll=1022971, marks=99, email='Cordie Harnois_Clementina Menke@OOP.com'),
 Row(age=28, gender='Male', name='Annika Hoffman', course='DB', roll=1031544, marks=44, email='Dustin Feagins_Somer Stoecker@DB.com'),
 Row(age=29, gender='Female', name='Hubert Oliveras', course='DSA', roll=1041483, marks=28, email='Billi Clore_Santa Kerfien@DSA.com'),
 Row(age=28, gender='Male', name='Billi Clore', course='MVC', roll=1052566, marks=78, email='Naoma Fritts_Margene Moores@DSA.com'),
 Row(age=28, gender='Female', name='Nicole Harwood', course='MVC', roll=1061068, marks=82, email='Santa Kerfien_Hubert Oliveras@MVC.com'),
 Row(age=29, gender='Male', name='Clementina Menke', course='PF', roll=1071717, marks=54, email='Celeste Lollis_Leontine Phillips@OOP.com'),
 Row(age=28, gender='Female', name='Claude Panos', course='OOP', roll=1081294, marks=94, email='Kizzy Brenner_Anna Santos@OOP.com'),
 Row(age=29, gender='Male', name='Donna Yerby', course='DSA', roll=1092702, marks=79, email='Marylee Capasso_Alberta Freund@OOP.com'),
 Row(age=29, gender='Female', name='Maybell Duguay', course='MVC', roll=1102536, marks=22, email='Somer Stoecker_Marylee Capasso@OOP.com'),
 Row(age=29, gender='Male', name='Abram Nagao', course='PF', roll=1112161, marks=42, email='Nicole Harwood_Niki Klimek@DB.com'),
 Row(age=28, gender='Female', name='Bonita Higuera', course='DSA', roll=1122348, marks=51, email='Somer Stoecker_Jenna Montague@DB.com'),
 Row(age=29, gender='Female', name='Melani Engberg', course='OOP', roll=1132093, marks=76, email='Kena Wild_Neda Briski@Cloud.com'),
 Row(age=29, gender='Female', name='Marylee Capasso', course='OOP', roll=1142653, marks=61, email='Cordie Harnois_Alberta Freund@DSA.com'),
 Row(age=29, gender='Male', name='Nicole Harwood', course='Cloud', roll=1152571, marks=62, email='Latia Vanhoose_Maybell Duguay@PF.com'),
 Row(age=29, gender='Female', name='Dustin Feagins', course='OOP', roll=1161607, marks=37, email='Eda Neathery_Marylee Capasso@MVC.com'),
 Row(age=28, gender='Female', name='Niki Klimek', course='PF', roll=1172784, marks=24, email='Jeannetta Golden_Abram Nagao@MVC.com'),
 Row(age=29, gender='Female', name='Abram Nagao', course='DSA', roll=1181007, marks=57, email='Anna Santos_Anna Santos@DSA.com'),
 Row(age=28, gender='Male', name='Jalisa Swenson', course='PF', roll=1192555, marks=77, email='Marylee Capasso_Celeste Lollis@Cloud.com'),
 Row(age=29, gender='Female', name='Ernest Rossbach', course='MVC', roll=1201427, marks=80, email='Elenore Choy_Jenna Montague@OOP.com'),
 Row(age=28, gender='Male', name='Nicole Harwood', course='DB', roll=1211495, marks=28, email='Melani Engberg_Jc Andrepont@Cloud.com'),
 Row(age=29, gender='Female', name='Claude Panos', course='DB', roll=1222887, marks=75, email='Hubert Oliveras_Somer Stoecker@Cloud.com'),
 Row(age=28, gender='Female', name='Cordie Harnois', course='OOP', roll=1231943, marks=68, email='Mickey Cortright_Kizzy Brenner@OOP.com'),
 Row(age=28, gender='Male', name='Nicole Harwood', course='OOP', roll=1242426, marks=71, email='Billi Clore_Loris Crossett@Cloud.com'),
 Row(age=28, gender='Male', name='Gonzalo Ferebee', course='Cloud', roll=1251176, marks=60, email='Santa Kerfien_Tamera Blakley@PF.com'),
 Row(age=29, gender='Male', name='Jalisa Swenson', course='Cloud', roll=1261533, marks=70, email='Dustin Feagins_Nicole Harwood@PF.com'),
 Row(age=28, gender='Female', name='Eda Neathery', course='Cloud', roll=1272870, marks=69, email='Somer Stoecker_Dustin Feagins@DB.com'),
 Row(age=28, gender='Female', name='Toshiko Hillyard', course='DSA', roll=1282835, marks=79, email='Somer Stoecker_Toshiko Hillyard@OOP.com'),
 Row(age=28, gender='Male', name='Paris Hutton', course='MVC', roll=1292279, marks=26, email='Paris Hutton_Eda Neathery@DSA.com'),
 Row(age=29, gender='Female', name='Niki Klimek', course='DB', roll=1301784, marks=24, email='Celeste Lollis_Tamera Blakley@DB.com'),
 Row(age=28, gender='Male', name='Bonita Higuera', course='Cloud', roll=1312294, marks=94, email='Eda Neathery_Priscila Tavernier@PF.com'),
 Row(age=28, gender='Female', name='Leontine Phillips', course='MVC', roll=1322629, marks=87, email='Judie Chipps_Michelle Ruggiero@Cloud.com'),
 Row(age=29, gender='Male', name='Jalisa Swenson', course='PF', roll=1332072, marks=88, email='Billi Clore_Kizzy Brenner@Cloud.com'),
 Row(age=28, gender='Male', name='Clementina Menke', course='OOP', roll=1341574, marks=46, email='Elenore Choy_Mickey Cortright@DB.com'),
 Row(age=28, gender='Male', name='Gonzalo Ferebee', course='PF', roll=1352348, marks=95, email='Neda Briski_Somer Stoecker@DB.com'),
 Row(age=29, gender='Female', name='Jalisa Swenson', course='DSA', roll=1362151, marks=51, email='Lawanda Wohlwend_Jenna Montague@PF.com'),
 Row(age=28, gender='Male', name='Lawanda Wohlwend', course='PF', roll=1372552, marks=88, email='Hubert Oliveras_Tijuana Kropf@DSA.com'),
 Row(age=28, gender='Male', name='Abram Nagao', course='DSA', roll=1382959, marks=66, email='Michelle Ruggiero_Kena Wild@OOP.com'),
 Row(age=29, gender='Female', name='Hubert Oliveras', course='Cloud', roll=1392791, marks=94, email='Anna Santos_Alberta Freund@Cloud.com'),
 Row(age=28, gender='Male', name='Bonita Higuera', course='Cloud', roll=1401526, marks=24, email='Jc Andrepont_Cheri Kenney@Cloud.com'),
 Row(age=29, gender='Female', name='Clementina Menke', course='OOP', roll=1412376, marks=65, email='Elenore Choy_Latia Vanhoose@DSA.com'),
 Row(age=29, gender='Female', name='Mickey Cortright', course='Cloud', roll=1421542, marks=71, email='Latia Vanhoose_Kena Wild@OOP.com'),
 Row(age=29, gender='Female', name='Leontine Phillips', course='DB', roll=1432252, marks=67, email='Billi Clore_Sheryll Towler@DB.com'),
 Row(age=28, gender='Female', name='Nicole Harwood', course='PF', roll=1441367, marks=95, email='Jc Andrepont_Anna Santos@DSA.com'),
 Row(age=28, gender='Female', name='Gonzalo Ferebee', course='DB', roll=1451513, marks=69, email='Claude Panos_Tamera Blakley@PF.com'),
 Row(age=29, gender='Female', name='Judie Chipps', course='DB', roll=1461078, marks=31, email='Tijuana Kropf_Billi Clore@OOP.com'),

In [12]:
rdd.filter(lambda x: x['gender']=="Male").collect()

[Row(age=28, gender='Male', name='Celeste Lollis', course='PF', roll=21267, marks=45, email='Jeannetta Golden_Jenna Montague@DSA.com'),
 Row(age=28, gender='Male', name='Sheryll Towler', course='DSA', roll=41487, marks=41, email='Claude Panos_Judie Chipps@OOP.com'),
 Row(age=28, gender='Male', name='Margene Moores', course='MVC', roll=52771, marks=32, email='Toshiko Hillyard_Clementina Menke@MVC.com'),
 Row(age=28, gender='Male', name='Neda Briski', course='OOP', roll=61973, marks=69, email='Alberta Freund_Elenore Choy@DB.com'),
 Row(age=28, gender='Male', name='Celeste Lollis', course='MVC', roll=81492, marks=64, email='Nicole Harwood_Claude Panos@MVC.com'),
 Row(age=29, gender='Male', name='Cordie Harnois', course='OOP', roll=92882, marks=51, email='Judie Chipps_Clementina Menke@MVC.com'),
 Row(age=29, gender='Male', name='Ernest Rossbach', course='DB', roll=111449, marks=53, email='Maybell Duguay_Abram Nagao@OOP.com'),
 Row(age=29, gender='Male', name='Neda Briski', course='PF', roll=141770, marks=42, email='Margene Moores_Michelle Ruggiero@MVC.com'),
 Row(age=29, gender='Male', name='Loris Crossett', course='MVC', roll=161771, marks=36, email='Mitzi Seldon_Jenna Montague@MVC.com'),
 Row(age=29, gender='Male', name='Annika Hoffman', course='OOP', roll=171660, marks=22, email='Taryn Brownlee_Mitzi Seldon@MVC.com'),
 Row(age=29, gender='Male', name='Santa Kerfien', course='PF', roll=182129, marks=56, email='Judie Chipps_Taryn Brownlee@Cloud.com'),
 Row(age=28, gender='Male', name='Hubert Oliveras', course='OOP', roll=351719, marks=63, email='Lawanda Wohlwend_Abram Nagao@MVC.com'),
 Row(age=28, gender='Male', name='Sebrina Maresca', course='PF', roll=361316, marks=62, email='Nicole Harwood_Latia Vanhoose@DB.com'),
 Row(age=29, gender='Male', name='Jalisa Swenson', course='PF', roll=372873, marks=45, email='Ernest Rossbach_Toshiko Hillyard@DB.com'),
 Row(age=28, gender='Male', name='Kizzy Brenner', course='DB', roll=381712, marks=36, email='Paris Hutton_Kena Wild@MVC.com'),
 Row(age=28, gender='Male', name='Toshiko Hillyard', course='DB', roll=392218, marks=47, email='Leontine Phillips_Billi Clore@MVC.com'),
 Row(age=28, gender='Male', name='Elenore Choy', course='PF', roll=422704, marks=66, email='Marylee Capasso_Nicole Harwood@MVC.com'),
 Row(age=28, gender='Male', name='Dustin Feagins', course='PF', roll=461839, marks=51, email='Neda Briski_Elenore Choy@Cloud.com'),
 Row(age=29, gender='Male', name='Annika Hoffman', course='OOP', roll=472550, marks=35, email='Mitzi Seldon_Abram Nagao@DSA.com'),
 Row(age=29, gender='Male', name='Paris Hutton', course='DB', roll=481229, marks=57, email='Clementina Menke_Paris Hutton@MVC.com'),
 Row(age=29, gender='Male', name='Billi Clore', course='Cloud', roll=512047, marks=76, email='Taryn Brownlee_Judie Chipps@DSA.com'),
 Row(age=29, gender='Male', name='Toshiko Hillyard', course='OOP', roll=521221, marks=77, email='Hubert Oliveras_Latia Vanhoose@MVC.com'),
 Row(age=28, gender='Male', name='Margene Moores', course='PF', roll=531530, marks=53, email='Cheri Kenney_Melani Engberg@OOP.com'),
 Row(age=29, gender='Male', name='Celeste Lollis', course='DSA', roll=562065, marks=85, email='Jc Andrepont_Melani Engberg@OOP.com'),
 Row(age=28, gender='Male', name='Marylee Capasso', course='OOP', roll=581756, marks=52, email='Jeannetta Golden_Loris Crossett@MVC.com'),
 Row(age=29, gender='Male', name='Maybell Duguay', course='DSA', roll=592061, marks=83, email='Eda Neathery_Jenna Montague@Cloud.com'),
 Row(age=28, gender='Male', name='Mitzi Seldon', course='DSA', roll=622981, marks=45, email='Lawanda Wohlwend_Loris Crossett@DSA.com'),
 Row(age=28, gender='Male', name='Priscila Tavernier', course='PF', roll=642594, marks=27, email='Marylee Capasso_Claude Panos@DSA.com'),
 Row(age=29, gender='Male', name='Tamera Blakley', course='MVC', roll=651649, marks=92, email='Latia Vanhoose_Toshiko Hillyard@MVC.com'),
 Row(age=28, gender='Male', name='Sheryll Towler', course='MVC', roll=661079, marks=89, email='Tijuana Kropf_Mickey Cortright@DB.com'),
 Row(age=29, gender='Male', name='Hubert Oliveras', course='MVC', roll=672451, marks=28, email='Annika Hoffman_Mickey Cortright@DSA.com'),
 Row(age=29, gender='Male', name='Sheryll Towler', course='PF', roll=682533, marks=42, email='Billi Clore_Anna Santos@PF.com'),
 Row(age=29, gender='Male', name='Maybell Duguay', course='PF', roll=701486, marks=99, email='Clementina Menke_Latia Vanhoose@Cloud.com'),
 Row(age=29, gender='Male', name='Jenna Montague', course='MVC', roll=711153, marks=45, email='Marylee Capasso_Hubert Oliveras@DB.com'),
 Row(age=28, gender='Male', name='Annika Hoffman', course='Cloud', roll=722193, marks=55, email='Taryn Brownlee_Elenore Choy@DB.com'),
 Row(age=29, gender='Male', name='Jeannetta Golden', course='MVC', roll=741875, marks=57, email='Sheryll Towler_Cheri Kenney@DSA.com'),
 Row(age=29, gender='Male', name='Paris Hutton', course='MVC', roll=752504, marks=22, email='Elenore Choy_Elenore Choy@DB.com'),
 Row(age=28, gender='Male', name='Alberta Freund', course='PF', roll=781061, marks=75, email='Leontine Phillips_Bonita Higuera@PF.com'),
 Row(age=28, gender='Male', name='Anna Santos', course='OOP', roll=822396, marks=47, email='Leontine Phillips_Gonzalo Ferebee@Cloud.com'),
 Row(age=28, gender='Male', name='Sheryll Towler', course='DSA', roll=831562, marks=59, email='Kena Wild_Gonzalo Ferebee@Cloud.com'),
 Row(age=29, gender='Male', name='Neda Briski', course='PF', roll=842515, marks=68, email='Neda Briski_Hubert Oliveras@OOP.com'),
 Row(age=29, gender='Male', name='Clementina Menke', course='DB', roll=882200, marks=76, email='Michelle Ruggiero_Jenna Montague@MVC.com'),
 Row(age=28, gender='Male', name='Margene Moores', course='DSA', roll=892010, marks=93, email='Anna Santos_Naoma Fritts@DSA.com'),
 Row(age=29, gender='Male', name='Loris Crossett', course='PF', roll=911593, marks=46, email='Gonzalo Ferebee_Mitzi Seldon@PF.com'),
 Row(age=29, gender='Male', name='Naoma Fritts', course='DB', roll=931295, marks=79, email='Hubert Oliveras_Sheryll Towler@DSA.com'),
 Row(age=29, gender='Male', name='Abram Nagao', course='MVC', roll=962235, marks=32, email='Jenna Montague_Gonzalo Ferebee@DSA.com'),
 Row(age=29, gender='Male', name='Niki Klimek', course='PF', roll=982443, marks=94, email='Santa Kerfien_Kizzy Brenner@DB.com'),
 Row(age=28, gender='Male', name='Jenna Montague', course='DSA', roll=1002103, marks=36, email='Melani Engberg_Hubert Oliveras@PF.com'),
 Row(age=29, gender='Male', name='Michelle Ruggiero', course='DSA', roll=1022971, marks=99, email='Cordie Harnois_Clementina Menke@OOP.com'),
 Row(age=28, gender='Male', name='Annika Hoffman', course='DB', roll=1031544, marks=44, email='Dustin Feagins_Somer Stoecker@DB.com'),
 Row(age=28, gender='Male', name='Billi Clore', course='MVC', roll=1052566, marks=78, email='Naoma Fritts_Margene Moores@DSA.com'),
 Row(age=29, gender='Male', name='Clementina Menke', course='PF', roll=1071717, marks=54, email='Celeste Lollis_Leontine Phillips@OOP.com'),
 Row(age=29, gender='Male', name='Donna Yerby', course='DSA', roll=1092702, marks=79, email='Marylee Capasso_Alberta Freund@OOP.com'),
 Row(age=29, gender='Male', name='Abram Nagao', course='PF', roll=1112161, marks=42, email='Nicole Harwood_Niki Klimek@DB.com'),
 Row(age=29, gender='Male', name='Nicole Harwood', course='Cloud', roll=1152571, marks=62, email='Latia Vanhoose_Maybell Duguay@PF.com'),
 Row(age=28, gender='Male', name='Jalisa Swenson', course='PF', roll=1192555, marks=77, email='Marylee Capasso_Celeste Lollis@Cloud.com'),
 Row(age=28, gender='Male', name='Nicole Harwood', course='DB', roll=1211495, marks=28, email='Melani Engberg_Jc Andrepont@Cloud.com'),
 Row(age=28, gender='Male', name='Nicole Harwood', course='OOP', roll=1242426, marks=71, email='Billi Clore_Loris Crossett@Cloud.com'),
 Row(age=28, gender='Male', name='Gonzalo Ferebee', course='Cloud', roll=1251176, marks=60, email='Santa Kerfien_Tamera Blakley@PF.com'),
 Row(age=29, gender='Male', name='Jalisa Swenson', course='Cloud', roll=1261533, marks=70, email='Dustin Feagins_Nicole Harwood@PF.com'),
 Row(age=28, gender='Male', name='Paris Hutton', course='MVC', roll=1292279, marks=26, email='Paris Hutton_Eda Neathery@DSA.com'),
 Row(age=28, gender='Male', name='Bonita Higuera', course='Cloud', roll=1312294, marks=94, email='Eda Neathery_Priscila Tavernier@PF.com'),
 Row(age=29, gender='Male', name='Jalisa Swenson', course='PF', roll=1332072, marks=88, email='Billi Clore_Kizzy Brenner@Cloud.com'),
 Row(age=28, gender='Male', name='Clementina Menke', course='OOP', roll=1341574, marks=46, email='Elenore Choy_Mickey Cortright@DB.com'),
 Row(age=28, gender='Male', name='Gonzalo Ferebee', course='PF', roll=1352348, marks=95, email='Neda Briski_Somer Stoecker@DB.com'),
 Row(age=28, gender='Male', name='Lawanda Wohlwend', course='PF', roll=1372552, marks=88, email='Hubert Oliveras_Tijuana Kropf@DSA.com'),
 Row(age=28, gender='Male', name='Abram Nagao', course='DSA', roll=1382959, marks=66, email='Michelle Ruggiero_Kena Wild@OOP.com'),
 Row(age=28, gender='Male', name='Bonita Higuera', course='Cloud', roll=1401526, marks=24, email='Jc Andrepont_Cheri Kenney@Cloud.com'),
 Row(age=29, gender='Male', name='Niki Klimek', course='MVC', roll=1472917, marks=36, email='Sebrina Maresca_Sheryll Towler@MVC.com'),
 Row(age=28, gender='Male', name='Jc Andrepont', course='DSA', roll=1492828, marks=78, email='Celeste Lollis_Kizzy Brenner@MVC.com'),
 Row(age=28, gender='Male', name='Hubert Oliveras', course='PF', roll=1521724, marks=91, email='Eda Neathery_Jeannetta Golden@MVC.com'),
 Row(age=28, gender='Male', name='Paris Hutton', course='MVC', roll=1602777, marks=53, email='Sheryll Towler_Loris Crossett@DSA.com'),
 Row(age=28, gender='Male', name='Marylee Capasso', course='DB', roll=1611411, marks=96, email='Annika Hoffman_Loris Crossett@PF.com'),
 Row(age=28, gender='Male', name='Anna Santos', course='OOP', roll=1621905, marks=24, email='Elenore Choy_Santa Kerfien@DB.com'),
 Row(age=28, gender='Male', name='Neda Briski', course='DSA', roll=1632185, marks=93, email='Clementina Menke_Toshiko Hillyard@Cloud.com'),
 Row(age=29, gender='Male', name='Alberta Freund', course='DB', roll=1671638, marks=98, email='Clementina Menke_Jalisa Swenson@Cloud.com'),
 Row(age=28, gender='Male', name='Celeste Lollis', course='DB', roll=1692106, marks=36, email='Neda Briski_Abram Nagao@MVC.com'),
 Row(age=29, gender='Male', name='Nicole Harwood', course='MVC', roll=1761454, marks=34, email='Taryn Brownlee_Billi Clore@DSA.com'),
 Row(age=29, gender='Male', name='Claude Panos', course='DSA', roll=1771605, marks=50, email='Claude Panos_Tamera Blakley@OOP.com'),
 Row(age=29, gender='Male', name='Dustin Feagins', course='DB', roll=1782045, marks=81, email='Cordie Harnois_Toshiko Hillyard@OOP.com'),
 Row(age=29, gender='Male', name='Toshiko Hillyard', course='DSA', roll=1791364, marks=50, email='Jc Andrepont_Nicole Harwood@MVC.com'),
 Row(age=28, gender='Male', name='Alberta Freund', course='Cloud', roll=1802934, marks=24, email='Maybell Duguay_Paris Hutton@PF.com'),
 Row(age=29, gender='Male', name='Latia Vanhoose', course='Cloud', roll=1832268, marks=60, email='Marylee Capasso_Santa Kerfien@MVC.com'),
 Row(age=29, gender='Male', name='Alberta Freund', course='OOP', roll=1841931, marks=37, email='Jenna Montague_Taryn Brownlee@Cloud.com'),
 Row(age=29, gender='Male', name='Celeste Lollis', course='PF', roll=1861656, marks=67, email='Niki Klimek_Lawanda Wohlwend@DB.com'),
 Row(age=29, gender='Male', name='Tijuana Kropf', course='DB', roll=1882795, marks=92, email='Hubert Oliveras_Elenore Choy@Cloud.com'),
 Row(age=28, gender='Male', name='Somer Stoecker', course='Cloud', roll=1891261, marks=30, email='Taryn Brownlee_Sheryll Towler@PF.com'),
 Row(age=28, gender='Male', name='Ernest Rossbach', course='DB', roll=1901492, marks=54, email='Latia Vanhoose_Jc Andrepont@MVC.com'),
 Row(age=29, gender='Male', name='Sebrina Maresca', course='PF', roll=1932455, marks=23, email='Tijuana Kropf_Naoma Fritts@Cloud.com'),
 Row(age=29, gender='Male', name='Marylee Capasso', course='DSA', roll=1942185, marks=37, email='Tijuana Kropf_Latia Vanhoose@DSA.com'),
 Row(age=29, gender='Male', name='Jeannetta Golden', course='Cloud', roll=1952763, marks=67, email='Jenna Montague_Jeannetta Golden@OOP.com'),
 Row(age=29, gender='Male', name='Niki Klimek', course='MVC', roll=1962371, marks=78, email='Marylee Capasso_Mickey Cortright@PF.com'),
 Row(age=29, gender='Male', name='Tamera Blakley', course='OOP', roll=1981124, marks=46, email='Taryn Brownlee_Eda Neathery@DB.com'),
 Row(age=28, gender='Male', name='Santa Kerfien', course='MVC', roll=1992202, marks=23, email='Annika Hoffman_Tamera Blakley@OOP.com'),
 Row(age=29, gender='Male', name='Somer Stoecker', course='OOP', roll=2011301, marks=47, email='Somer Stoecker_Anna Santos@MVC.com'),
 Row(age=28, gender='Male', name='Billi Clore', course='PF', roll=2022282, marks=77, email='Anna Santos_Claude Panos@Cloud.com'),
 Row(age=28, gender='Male', name='Kena Wild', course='DB', roll=2031530, marks=93, email='Jc Andrepont_Jc Andrepont@PF.com'),
 Row(age=28, gender='Male', name='Marylee Capasso', course='DSA', roll=2081560, marks=20, email='Sheryll Towler_Donna Yerby@Cloud.com'),
 Row(age=28, gender='Male', name='Neda Briski', course='Cloud', roll=2092176, marks=81, email='Celeste Lollis_Maybell Duguay@PF.com'),
 Row(age=29, gender='Male', name='Donna Yerby', course='DSA', roll=2102495, marks=97, email='Paris Hutton_Celeste Lollis@PF.com'),
 Row(age=29, gender='Male', name='Judie Chipps', course='DB', roll=2112234, marks=94, email='Dustin Feagins_Tamera Blakley@PF.com'),
 Row(age=29, gender='Male', name='Jeannetta Golden', course='MVC', roll=2132781, marks=93, email='Kizzy Brenner_Cheri Kenney@MVC.com'),
 Row(age=29, gender='Male', name='Naoma Fritts', course='PF', roll=2141246, marks=91, email='Mitzi Seldon_Cordie Harnois@Cloud.com'),
 Row(age=29, gender='Male', name='Somer Stoecker', course='MVC', roll=2151024, marks=36, email='Loris Crossett_Tamera Blakley@DB.com'),
 Row(age=28, gender='Male', name='Toshiko Hillyard', course='PF', roll=2162776, marks=54, email='Jenna Montague_Niki Klimek@MVC.com'),
 Row(age=28, gender='Male', name='Jeannetta Golden', course='DB', roll=2171387, marks=76, email='Cheri Kenney_Billi Clore@DB.com'),
 Row(age=29, gender='Male', name='Mitzi Seldon', course='Cloud', roll=2202649, marks=43, email='Santa Kerfien_Loris Crossett@Cloud.com'),
 Row(age=28, gender='Male', name='Jalisa Swenson', course='DSA', roll=2222704, marks=91, email='Judie Chipps_Jalisa Swenson@Cloud.com'),
 Row(age=28, gender='Male', name='Priscila Tavernier', course='OOP', roll=2232863, marks=60, email='Bonita Higuera_Lawanda Wohlwend@MVC.com'),
 Row(age=29, gender='Male', name='Margene Moores', course='Cloud', roll=2241434, marks=71, email='Mitzi Seldon_Michelle Ruggiero@Cloud.com'),
 Row(age=29, gender='Male', name='Annika Hoffman', course='PF', roll=2301940, marks=81, email='Jenna Montague_Sheryll Towler@Cloud.com'),
 Row(age=28, gender='Male', name='Kizzy Brenner', course='DB', roll=2322537, marks=56, email='Jenna Montague_Latia Vanhoose@MVC.com'),
 Row(age=29, gender='Male', name='Michelle Ruggiero', course='Cloud', roll=2332207, marks=72, email='Gonzalo Ferebee_Melani Engberg@OOP.com'),
 Row(age=29, gender='Male', name='Alberta Freund', course='DSA', roll=2341989, marks=68, email='Jeannetta Golden_Priscila Tavernier@PF.com'),
 Row(age=29, gender='Male', name='Mickey Cortright', course='OOP', roll=2361202, marks=59, email='Kizzy Brenner_Eda Neathery@MVC.com'),
 Row(age=29, gender='Male', name='Latia Vanhoose', course='OOP', roll=2372748, marks=94, email='Latia Vanhoose_Latia Vanhoose@OOP.com'),
 Row(age=29, gender='Male', name='Naoma Fritts', course='OOP', roll=2382829, marks=37, email='Ernest Rossbach_Celeste Lollis@PF.com'),
 Row(age=28, gender='Male', name='Melani Engberg', course='MVC', roll=2412019, marks=54, email='Latia Vanhoose_Melani Engberg@DSA.com'),
 Row(age=28, gender='Male', name='Sebrina Maresca', course='Cloud', roll=2452108, marks=41, email='Billi Clore_Loris Crossett@DSA.com'),
 Row(age=28, gender='Male', name='Judie Chipps', course='DB', roll=2461986, marks=53, email='Niki Klimek_Judie Chipps@MVC.com'),
 Row(age=29, gender='Male', name='Jenna Montague', course='DSA', roll=2472773, marks=81, email='Margene Moores_Bonita Higuera@DSA.com'),
 Row(age=29, gender='Male', name='Cheri Kenney', course='Cloud', roll=2491705, marks=64, email='Toshiko Hillyard_Mickey Cortright@PF.com'),
 Row(age=28, gender='Male', name='Priscila Tavernier', course='Cloud', roll=2552194, marks=42, email='Jeannetta Golden_Abram Nagao@PF.com'),
 Row(age=28, gender='Male', name='Claude Panos', course='OOP', roll=2562357, marks=50, email='Naoma Fritts_Anna Santos@Cloud.com'),
 Row(age=28, gender='Male', name='Gonzalo Ferebee', course='MVC', roll=2572197, marks=43, email='Marylee Capasso_Jc Andrepont@DB.com'),
 Row(age=29, gender='Male', name='Nicole Harwood', course='Cloud', roll=2581369, marks=26, email='Paris Hutton_Alberta Freund@MVC.com'),
 Row(age=28, gender='Male', name='Paris Hutton', course='OOP', roll=2592369, marks=60, email='Taryn Brownlee_Sheryll Towler@OOP.com'),
 Row(age=28, gender='Male', name='Sheryll Towler', course='DSA', roll=2612360, marks=27, email='Celeste Lollis_Paris Hutton@OOP.com'),
 Row(age=28, gender='Male', name='Mitzi Seldon', course='DB', roll=2622118, marks=55, email='Mickey Cortright_Mitzi Seldon@MVC.com'),
 Row(age=28, gender='Male', name='Billi Clore', course='PF', roll=2642909, marks=58, email='Loris Crossett_Sebrina Maresca@OOP.com'),
 Row(age=28, gender='Male', name='Abram Nagao', course='Cloud', roll=2652463, marks=21, email='Eda Neathery_Annika Hoffman@Cloud.com'),
 Row(age=29, gender='Male', name='Tamera Blakley', course='DSA', roll=2661934, marks=23, email='Alberta Freund_Tijuana Kropf@Cloud.com'),
 Row(age=28, gender='Male', name='Mitzi Seldon', course='PF', roll=2701239, marks=76, email='Alberta Freund_Cordie Harnois@Cloud.com'),
 Row(age=29, gender='Male', name='Sebrina Maresca', course='PF', roll=2712040, marks=23, email='Jeannetta Golden_Judie Chipps@DB.com'),
 Row(age=29, gender='Male', name='Somer Stoecker', course='PF', roll=2721652, marks=36, email='Tijuana Kropf_Michelle Ruggiero@Cloud.com'),
 Row(age=28, gender='Male', name='Santa Kerfien', course='DB', roll=2732421, marks=79, email='Claude Panos_Alberta Freund@DB.com'),
 Row(age=28, gender='Male', name='Clementina Menke', course='DSA', roll=2772189, marks=98, email='Donna Yerby_Judie Chipps@PF.com'),
 Row(age=29, gender='Male', name='Tijuana Kropf', course='Cloud', roll=2781801, marks=68, email='Alberta Freund_Cordie Harnois@Cloud.com'),
 Row(age=29, gender='Male', name='Leontine Phillips', course='PF', roll=2832158, marks=26, email='Margene Moores_Claude Panos@MVC.com'),
 Row(age=29, gender='Male', name='Abram Nagao', course='DB', roll=2841061, marks=25, email='Leontine Phillips_Toshiko Hillyard@Cloud.com'),
 Row(age=28, gender='Male', name='Loris Crossett', course='OOP', roll=2852490, marks=25, email='Loris Crossett_Donna Yerby@DSA.com'),
 Row(age=28, gender='Male', name='Michelle Ruggiero', course='DB', roll=2891164, marks=60, email='Gonzalo Ferebee_Priscila Tavernier@DSA.com'),
 Row(age=29, gender='Male', name='Niki Klimek', course='DB', roll=2912538, marks=67, email='Jc Andrepont_Mitzi Seldon@DSA.com'),
 Row(age=28, gender='Male', name='Gonzalo Ferebee', course='Cloud', roll=2922041, marks=38, email='Clementina Menke_Taryn Brownlee@OOP.com'),
 Row(age=29, gender='Male', name='Melani Engberg', course='DB', roll=2941257, marks=98, email='Claude Panos_Kena Wild@DB.com'),
 Row(age=29, gender='Male', name='Billi Clore', course='DSA', roll=2952091, marks=52, email='Jenna Montague_Mickey Cortright@DB.com'),
 Row(age=29, gender='Male', name='Claude Panos', course='PF', roll=2961015, marks=33, email='Elenore Choy_Santa Kerfien@DSA.com'),

In [17]:
rdd.filter(lambda x: x['age']==28 and x['gender'] =='Male').collect()

[Row(age=28, gender='Male', name='Celeste Lollis', course='PF', roll=21267, marks=45, email='Jeannetta Golden_Jenna Montague@DSA.com'),
 Row(age=28, gender='Male', name='Sheryll Towler', course='DSA', roll=41487, marks=41, email='Claude Panos_Judie Chipps@OOP.com'),
 Row(age=28, gender='Male', name='Margene Moores', course='MVC', roll=52771, marks=32, email='Toshiko Hillyard_Clementina Menke@MVC.com'),
 Row(age=28, gender='Male', name='Neda Briski', course='OOP', roll=61973, marks=69, email='Alberta Freund_Elenore Choy@DB.com'),
 Row(age=28, gender='Male', name='Celeste Lollis', course='MVC', roll=81492, marks=64, email='Nicole Harwood_Claude Panos@MVC.com'),
 Row(age=28, gender='Male', name='Hubert Oliveras', course='OOP', roll=351719, marks=63, email='Lawanda Wohlwend_Abram Nagao@MVC.com'),
 Row(age=28, gender='Male', name='Sebrina Maresca', course='PF', roll=361316, marks=62, email='Nicole Harwood_Latia Vanhoose@DB.com'),
 Row(age=28, gender='Male', name='Kizzy Brenner', course='DB', roll=381712, marks=36, email='Paris Hutton_Kena Wild@MVC.com'),
 Row(age=28, gender='Male', name='Toshiko Hillyard', course='DB', roll=392218, marks=47, email='Leontine Phillips_Billi Clore@MVC.com'),
 Row(age=28, gender='Male', name='Elenore Choy', course='PF', roll=422704, marks=66, email='Marylee Capasso_Nicole Harwood@MVC.com'),
 Row(age=28, gender='Male', name='Dustin Feagins', course='PF', roll=461839, marks=51, email='Neda Briski_Elenore Choy@Cloud.com'),
 Row(age=28, gender='Male', name='Margene Moores', course='PF', roll=531530, marks=53, email='Cheri Kenney_Melani Engberg@OOP.com'),
 Row(age=28, gender='Male', name='Marylee Capasso', course='OOP', roll=581756, marks=52, email='Jeannetta Golden_Loris Crossett@MVC.com'),
 Row(age=28, gender='Male', name='Mitzi Seldon', course='DSA', roll=622981, marks=45, email='Lawanda Wohlwend_Loris Crossett@DSA.com'),
 Row(age=28, gender='Male', name='Priscila Tavernier', course='PF', roll=642594, marks=27, email='Marylee Capasso_Claude Panos@DSA.com'),
 Row(age=28, gender='Male', name='Sheryll Towler', course='MVC', roll=661079, marks=89, email='Tijuana Kropf_Mickey Cortright@DB.com'),
 Row(age=28, gender='Male', name='Annika Hoffman', course='Cloud', roll=722193, marks=55, email='Taryn Brownlee_Elenore Choy@DB.com'),
 Row(age=28, gender='Male', name='Alberta Freund', course='PF', roll=781061, marks=75, email='Leontine Phillips_Bonita Higuera@PF.com'),
 Row(age=28, gender='Male', name='Anna Santos', course='OOP', roll=822396, marks=47, email='Leontine Phillips_Gonzalo Ferebee@Cloud.com'),
 Row(age=28, gender='Male', name='Sheryll Towler', course='DSA', roll=831562, marks=59, email='Kena Wild_Gonzalo Ferebee@Cloud.com'),
 Row(age=28, gender='Male', name='Margene Moores', course='DSA', roll=892010, marks=93, email='Anna Santos_Naoma Fritts@DSA.com'),
 Row(age=28, gender='Male', name='Jenna Montague', course='DSA', roll=1002103, marks=36, email='Melani Engberg_Hubert Oliveras@PF.com'),
 Row(age=28, gender='Male', name='Annika Hoffman', course='DB', roll=1031544, marks=44, email='Dustin Feagins_Somer Stoecker@DB.com'),
 Row(age=28, gender='Male', name='Billi Clore', course='MVC', roll=1052566, marks=78, email='Naoma Fritts_Margene Moores@DSA.com'),
 Row(age=28, gender='Male', name='Jalisa Swenson', course='PF', roll=1192555, marks=77, email='Marylee Capasso_Celeste Lollis@Cloud.com'),
 Row(age=28, gender='Male', name='Nicole Harwood', course='DB', roll=1211495, marks=28, email='Melani Engberg_Jc Andrepont@Cloud.com'),
 Row(age=28, gender='Male', name='Nicole Harwood', course='OOP', roll=1242426, marks=71, email='Billi Clore_Loris Crossett@Cloud.com'),
 Row(age=28, gender='Male', name='Gonzalo Ferebee', course='Cloud', roll=1251176, marks=60, email='Santa Kerfien_Tamera Blakley@PF.com'),
 Row(age=28, gender='Male', name='Paris Hutton', course='MVC', roll=1292279, marks=26, email='Paris Hutton_Eda Neathery@DSA.com'),
 Row(age=28, gender='Male', name='Bonita Higuera', course='Cloud', roll=1312294, marks=94, email='Eda Neathery_Priscila Tavernier@PF.com'),
 Row(age=28, gender='Male', name='Clementina Menke', course='OOP', roll=1341574, marks=46, email='Elenore Choy_Mickey Cortright@DB.com'),
 Row(age=28, gender='Male', name='Gonzalo Ferebee', course='PF', roll=1352348, marks=95, email='Neda Briski_Somer Stoecker@DB.com'),
 Row(age=28, gender='Male', name='Lawanda Wohlwend', course='PF', roll=1372552, marks=88, email='Hubert Oliveras_Tijuana Kropf@DSA.com'),
 Row(age=28, gender='Male', name='Abram Nagao', course='DSA', roll=1382959, marks=66, email='Michelle Ruggiero_Kena Wild@OOP.com'),
 Row(age=28, gender='Male', name='Bonita Higuera', course='Cloud', roll=1401526, marks=24, email='Jc Andrepont_Cheri Kenney@Cloud.com'),
 Row(age=28, gender='Male', name='Jc Andrepont', course='DSA', roll=1492828, marks=78, email='Celeste Lollis_Kizzy Brenner@MVC.com'),
 Row(age=28, gender='Male', name='Hubert Oliveras', course='PF', roll=1521724, marks=91, email='Eda Neathery_Jeannetta Golden@MVC.com'),
 Row(age=28, gender='Male', name='Paris Hutton', course='MVC', roll=1602777, marks=53, email='Sheryll Towler_Loris Crossett@DSA.com'),
 Row(age=28, gender='Male', name='Marylee Capasso', course='DB', roll=1611411, marks=96, email='Annika Hoffman_Loris Crossett@PF.com'),
 Row(age=28, gender='Male', name='Anna Santos', course='OOP', roll=1621905, marks=24, email='Elenore Choy_Santa Kerfien@DB.com'),
 Row(age=28, gender='Male', name='Neda Briski', course='DSA', roll=1632185, marks=93, email='Clementina Menke_Toshiko Hillyard@Cloud.com'),
 Row(age=28, gender='Male', name='Celeste Lollis', course='DB', roll=1692106, marks=36, email='Neda Briski_Abram Nagao@MVC.com'),
 Row(age=28, gender='Male', name='Alberta Freund', course='Cloud', roll=1802934, marks=24, email='Maybell Duguay_Paris Hutton@PF.com'),
 Row(age=28, gender='Male', name='Somer Stoecker', course='Cloud', roll=1891261, marks=30, email='Taryn Brownlee_Sheryll Towler@PF.com'),
 Row(age=28, gender='Male', name='Ernest Rossbach', course='DB', roll=1901492, marks=54, email='Latia Vanhoose_Jc Andrepont@MVC.com'),
 Row(age=28, gender='Male', name='Santa Kerfien', course='MVC', roll=1992202, marks=23, email='Annika Hoffman_Tamera Blakley@OOP.com'),
 Row(age=28, gender='Male', name='Billi Clore', course='PF', roll=2022282, marks=77, email='Anna Santos_Claude Panos@Cloud.com'),
 Row(age=28, gender='Male', name='Kena Wild', course='DB', roll=2031530, marks=93, email='Jc Andrepont_Jc Andrepont@PF.com'),
 Row(age=28, gender='Male', name='Marylee Capasso', course='DSA', roll=2081560, marks=20, email='Sheryll Towler_Donna Yerby@Cloud.com'),
 Row(age=28, gender='Male', name='Neda Briski', course='Cloud', roll=2092176, marks=81, email='Celeste Lollis_Maybell Duguay@PF.com'),
 Row(age=28, gender='Male', name='Toshiko Hillyard', course='PF', roll=2162776, marks=54, email='Jenna Montague_Niki Klimek@MVC.com'),
 Row(age=28, gender='Male', name='Jeannetta Golden', course='DB', roll=2171387, marks=76, email='Cheri Kenney_Billi Clore@DB.com'),
 Row(age=28, gender='Male', name='Jalisa Swenson', course='DSA', roll=2222704, marks=91, email='Judie Chipps_Jalisa Swenson@Cloud.com'),
 Row(age=28, gender='Male', name='Priscila Tavernier', course='OOP', roll=2232863, marks=60, email='Bonita Higuera_Lawanda Wohlwend@MVC.com'),
 Row(age=28, gender='Male', name='Kizzy Brenner', course='DB', roll=2322537, marks=56, email='Jenna Montague_Latia Vanhoose@MVC.com'),
 Row(age=28, gender='Male', name='Melani Engberg', course='MVC', roll=2412019, marks=54, email='Latia Vanhoose_Melani Engberg@DSA.com'),
 Row(age=28, gender='Male', name='Sebrina Maresca', course='Cloud', roll=2452108, marks=41, email='Billi Clore_Loris Crossett@DSA.com'),
 Row(age=28, gender='Male', name='Judie Chipps', course='DB', roll=2461986, marks=53, email='Niki Klimek_Judie Chipps@MVC.com'),
 Row(age=28, gender='Male', name='Priscila Tavernier', course='Cloud', roll=2552194, marks=42, email='Jeannetta Golden_Abram Nagao@PF.com'),
 Row(age=28, gender='Male', name='Claude Panos', course='OOP', roll=2562357, marks=50, email='Naoma Fritts_Anna Santos@Cloud.com'),
 Row(age=28, gender='Male', name='Gonzalo Ferebee', course='MVC', roll=2572197, marks=43, email='Marylee Capasso_Jc Andrepont@DB.com'),
 Row(age=28, gender='Male', name='Paris Hutton', course='OOP', roll=2592369, marks=60, email='Taryn Brownlee_Sheryll Towler@OOP.com'),
 Row(age=28, gender='Male', name='Sheryll Towler', course='DSA', roll=2612360, marks=27, email='Celeste Lollis_Paris Hutton@OOP.com'),
 Row(age=28, gender='Male', name='Mitzi Seldon', course='DB', roll=2622118, marks=55, email='Mickey Cortright_Mitzi Seldon@MVC.com'),
 Row(age=28, gender='Male', name='Billi Clore', course='PF', roll=2642909, marks=58, email='Loris Crossett_Sebrina Maresca@OOP.com'),
 Row(age=28, gender='Male', name='Abram Nagao', course='Cloud', roll=2652463, marks=21, email='Eda Neathery_Annika Hoffman@Cloud.com'),
 Row(age=28, gender='Male', name='Mitzi Seldon', course='PF', roll=2701239, marks=76, email='Alberta Freund_Cordie Harnois@Cloud.com'),
 Row(age=28, gender='Male', name='Santa Kerfien', course='DB', roll=2732421, marks=79, email='Claude Panos_Alberta Freund@DB.com'),
 Row(age=28, gender='Male', name='Clementina Menke', course='DSA', roll=2772189, marks=98, email='Donna Yerby_Judie Chipps@PF.com'),
 Row(age=28, gender='Male', name='Loris Crossett', course='OOP', roll=2852490, marks=25, email='Loris Crossett_Donna Yerby@DSA.com'),
 Row(age=28, gender='Male', name='Michelle Ruggiero', course='DB', roll=2891164, marks=60, email='Gonzalo Ferebee_Priscila Tavernier@DSA.com'),
 Row(age=28, gender='Male', name='Gonzalo Ferebee', course='Cloud', roll=2922041, marks=38, email='Clementina Menke_Taryn Brownlee@OOP.com'),
 Row(age=28, gender='Male', name='Leontine Phillips', course='Cloud', roll=3011586, marks=76, email='Dustin Feagins_Alberta Freund@DB.com'),
 Row(age=28, gender='Male', name='Tijuana Kropf', course='DB', roll=3111175, marks=70, email='Latia Vanhoose_Somer Stoecker@DSA.com'),
 Row(age=28, gender='Male', name='Kizzy Brenner', course='MVC', roll=3121184, marks=29, email='Tijuana Kropf_Elenore Choy@DB.com'),
 Row(age=28, gender='Male', name='Lawanda Wohlwend', course='Cloud', roll=3181337, marks=39, email='Sebrina Maresca_Billi Clore@MVC.com'),
 Row(age=28, gender='Male', name='Tijuana Kropf', course='MVC', roll=3212517, marks=48, email='Somer Stoecker_Mickey Cortright@PF.com'),
 Row(age=28, gender='Male', name='Sheryll Towler', course='OOP', roll=3322308, marks=32, email='Clementina Menke_Naoma Fritts@OOP.com'),
 Row(age=28, gender='Male', name='Jenna Montague', course='OOP', roll=3331161, marks=98, email='Leontine Phillips_Judie Chipps@DSA.com'),
 Row(age=28, gender='Male', name='Mitzi Seldon', course='PF', roll=3342819, marks=68, email='Cheri Kenney_Naoma Fritts@PF.com'),
 Row(age=28, gender='Male', name='Clementina Menke', course='Cloud', roll=3352508, marks=95, email='Naoma Fritts_Mickey Cortright@Cloud.com'),
 Row(age=28, gender='Male', name='Niki Klimek', course='PF', roll=3381919, marks=97, email='Hubert Oliveras_Latia Vanhoose@DB.com'),
 Row(age=28, gender='Male', name='Taryn Brownlee', course='PF', roll=3491666, marks=76, email='Neda Briski_Priscila Tavernier@DB.com'),
 Row(age=28, gender='Male', name='Kizzy Brenner', course='Cloud', roll=3581303, marks=80, email='Margene Moores_Tamera Blakley@PF.com'),
 Row(age=28, gender='Male', name='Mickey Cortright', course='Cloud', roll=3612300, marks=92, email='Cordie Harnois_Sheryll Towler@OOP.com'),
 Row(age=28, gender='Male', name='Hubert Oliveras', course='Cloud', roll=3632954, marks=34, email='Ernest Rossbach_Annika Hoffman@OOP.com'),
 Row(age=28, gender='Male', name='Jalisa Swenson', course='PF', roll=3681989, marks=88, email='Toshiko Hillyard_Ernest Rossbach@DB.com'),
 Row(age=28, gender='Male', name='Jenna Montague', course='DSA', roll=3721359, marks=96, email='Naoma Fritts_Kizzy Brenner@MVC.com'),
 Row(age=28, gender='Male', name='Niki Klimek', course='OOP', roll=3742031, marks=82, email='Leontine Phillips_Toshiko Hillyard@Cloud.com'),
 Row(age=28, gender='Male', name='Claude Panos', course='DB', roll=3752819, marks=78, email='Toshiko Hillyard_Mickey Cortright@DB.com'),
 Row(age=28, gender='Male', name='Abram Nagao', course='DSA', roll=3781521, marks=45, email='Taryn Brownlee_Michelle Ruggiero@OOP.com'),
 Row(age=28, gender='Male', name='Maybell Duguay', course='Cloud', roll=3791855, marks=33, email='Tijuana Kropf_Lawanda Wohlwend@PF.com'),
 Row(age=28, gender='Male', name='Bonita Higuera', course='DB', roll=3802569, marks=77, email='Kena Wild_Kena Wild@OOP.com'),
 Row(age=28, gender='Male', name='Eda Neathery', course='Cloud', roll=3831006, marks=75, email='Donna Yerby_Loris Crossett@DSA.com'),
 Row(age=28, gender='Male', name='Santa Kerfien', course='PF', roll=3961803, marks=94, email='Jeannetta Golden_Latia Vanhoose@PF.com'),
 Row(age=28, gender='Male', name='Cordie Harnois', course='PF', roll=3991186, marks=69, email='Loris Crossett_Somer Stoecker@PF.com'),
 Row(age=28, gender='Male', name='Jeannetta Golden', course='PF', roll=4021336, marks=63, email='Latia Vanhoose_Loris Crossett@PF.com'),
 Row(age=28, gender='Male', name='Margene Moores', course='DSA', roll=4071164, marks=42, email='Billi Clore_Lawanda Wohlwend@DB.com'),
 Row(age=28, gender='Male', name='Paris Hutton', course='OOP', roll=4141149, marks=82, email='Maybell Duguay_Marylee Capasso@DB.com'),
 Row(age=28, gender='Male', name='Celeste Lollis', course='DSA', roll=4201845, marks=46, email='Gonzalo Ferebee_Clementina Menke@MVC.com'),
 Row(age=28, gender='Male', name='Santa Kerfien', course='DB', roll=4311493, marks=90, email='Tijuana Kropf_Anna Santos@PF.com'),
 Row(age=28, gender='Male', name='Clementina Menke', course='PF', roll=4341575, marks=89, email='Cordie Harnois_Marylee Capasso@DB.com'),
 Row(age=28, gender='Male', name='Toshiko Hillyard', course='Cloud', roll=4381862, marks=55, email='Anna Santos_Melani Engberg@MVC.com'),
 Row(age=28, gender='Male', name='Kizzy Brenner', course='Cloud', roll=4622328, marks=21, email='Leontine Phillips_Marylee Capasso@PF.com'),
 Row(age=28, gender='Male', name='Marylee Capasso', course='PF', roll=4642202, marks=94, email='Marylee Capasso_Elenore Choy@Cloud.com'),
 Row(age=28, gender='Male', name='Eda Neathery', course='DB', roll=4651622, marks=43, email='Priscila Tavernier_Hubert Oliveras@DSA.com'),
 Row(age=28, gender='Male', name='Elenore Choy', course='MVC', roll=4681842, marks=88, email='Paris Hutton_Toshiko Hillyard@DB.com'),
 Row(age=28, gender='Male', name='Alberta Freund', course='DB', roll=4802967, marks=80, email='Naoma Fritts_Elenore Choy@DSA.com'),
 Row(age=28, gender='Male', name='Cheri Kenney', course='PF', roll=4841631, marks=84, email='Abram Nagao_Naoma Fritts@MVC.com'),
 Row(age=28, gender='Male', name='Cheri Kenney', course='OOP', roll=4862694, marks=68, email='Leontine Phillips_Taryn Brownlee@DB.com'),
 Row(age=28, gender='Male', name='Clementina Menke', course='DSA', roll=4891815, marks=44, email='Kena Wild_Judie Chipps@PF.com'),
 Row(age=28, gender='Male', name='Santa Kerfien', course='DB', roll=4932764, marks=76, email='Nicole Harwood_Loris Crossett@PF.com'),
 Row(age=28, gender='Male', name='Mitzi Seldon', course='MVC', roll=4942910, marks=91, email='Tamera Blakley_Jenna Montague@DSA.com'),
 Row(age=28, gender='Male', name='Gonzalo Ferebee', course='MVC', roll=5071004, marks=72, email='Mitzi Seldon_Taryn Brownlee@DSA.com'),
 Row(age=28, gender='Male', name='Eda Neathery', course='PF', roll=5082430, marks=22, email='Leontine Phillips_Lawanda Wohlwend@MVC.com'),
 Row(age=28, gender='Male', name='Tijuana Kropf', course='DSA', roll=5092243, marks=85, email='Jenna Montague_Loris Crossett@OOP.com'),
 Row(age=28, gender='Male', name='Niki Klimek', course='DSA', roll=5172507, marks=99, email='Marylee Capasso_Elenore Choy@MVC.com'),
 Row(age=28, gender='Male', name='Jc Andrepont', course='Cloud', roll=5202136, marks=97, email='Jc Andrepont_Kena Wild@PF.com'),
 Row(age=28, gender='Male', name='Eda Neathery', course='MVC', roll=5231777, marks=56, email='Judie Chipps_Jalisa Swenson@OOP.com'),
 Row(age=28, gender='Male', name='Elenore Choy', course='MVC', roll=5241419, marks=81, email='Sebrina Maresca_Taryn Brownlee@PF.com'),
 Row(age=28, gender='Male', name='Clementina Menke', course='DSA', roll=5272838, marks=27, email='Clementina Menke_Eda Neathery@MVC.com'),
 Row(age=28, gender='Male', name='Taryn Brownlee', course='DB', roll=5311449, marks=25, email='Santa Kerfien_Lawanda Wohlwend@OOP.com'),
 Row(age=28, gender='Male', name='Donna Yerby', course='DB', roll=5321010, marks=65, email='Jc Andrepont_Tijuana Kropf@DB.com'),
 Row(age=28, gender='Male', name='Tamera Blakley', course='DSA', roll=5352713, marks=80, email='Jeannetta Golden_Neda Briski@Cloud.com'),
 Row(age=28, gender='Male', name='Lawanda Wohlwend', course='OOP', roll=5382684, marks=34, email='Jc Andrepont_Kena Wild@Cloud.com'),
 Row(age=28, gender='Male', name='Jc Andrepont', course='DSA', roll=5421958, marks=33, email='Lawanda Wohlwend_Leontine Phillips@DB.com'),
 Row(age=28, gender='Male', name='Anna Santos', course='DSA', roll=5502368, marks=84, email='Sebrina Maresca_Jc Andrepont@Cloud.com'),
 Row(age=28, gender='Male', name='Gonzalo Ferebee', course='PF', roll=5552593, marks=55, email='Jeannetta Golden_Dustin Feagins@Cloud.com'),
 Row(age=28, gender='Male', name='Abram Nagao', course='OOP', roll=5571082, marks=85, email='Santa Kerfien_Jalisa Swenson@PF.com'),
 Row(age=28, gender='Male', name='Michelle Ruggiero', course='PF', roll=5612879, marks=64, email='Tijuana Kropf_Maybell Duguay@PF.com'),
 Row(age=28, gender='Male', name='Cheri Kenney', course='Cloud', roll=5641528, marks=94, email='Sebrina Maresca_Leontine Phillips@OOP.com'),
 Row(age=28, gender='Male', name='Tamera Blakley', course='DB', roll=5661433, marks=76, email='Abram Nagao_Leontine Phillips@MVC.com'),
 Row(age=28, gender='Male', name='Annika Hoffman', course='OOP', roll=5672977, marks=38, email='Paris Hutton_Latia Vanhoose@DB.com'),
 Row(age=28, gender='Male', name='Naoma Fritts', course='OOP', roll=5791890, marks=45, email='Billi Clore_Jenna Montague@Cloud.com'),
 Row(age=28, gender='Male', name='Mickey Cortright', course='PF', roll=5812370, marks=39, email='Jenna Montague_Sheryll Towler@OOP.com'),
 Row(age=28, gender='Male', name='Sebrina Maresca', course='PF', roll=5902730, marks=34, email='Michelle Ruggiero_Claude Panos@DSA.com'),
 Row(age=28, gender='Male', name='Toshiko Hillyard', course='DSA', roll=5992644, marks=77, email='Jenna Montague_Tijuana Kropf@Cloud.com'),
 Row(age=28, gender='Male', name='Gonzalo Ferebee', course='MVC', roll=6032264, marks=71, email='Jeannetta Golden_Claude Panos@Cloud.com'),
 Row(age=28, gender='Male', name='Priscila Tavernier', course='DSA', roll=6082520, marks=89, email='Clementina Menke_Hubert Oliveras@DSA.com'),
 Row(age=28, gender='Male', name='Paris Hutton', course='DB', roll=6131084, marks=72, email='Tijuana Kropf_Abram Nagao@MVC.com'),
 Row(age=28, gender='Male', name='Tijuana Kropf', course='Cloud', roll=6281730, marks=83, email='Mickey Cortright_Celeste Lollis@Cloud.com'),
 Row(age=28, gender='Male', name='Alberta Freund', course='PF', roll=6291431, marks=68, email='Clementina Menke_Billi Clore@PF.com'),
 Row(age=28, gender='Male', name='Alberta Freund', course='PF', roll=6352910, marks=52, email='Judie Chipps_Maybell Duguay@Cloud.com'),
 Row(age=28, gender='Male', name='Annika Hoffman', course='MVC', roll=6381719, marks=48, email='Ernest Rossbach_Jc Andrepont@DSA.com'),
 Row(age=28, gender='Male', name='Lawanda Wohlwend', course='Cloud', roll=6391977, marks=39, email='Marylee Capasso_Melani Engberg@MVC.com'),
 Row(age=28, gender='Male', name='Naoma Fritts', course='DB', roll=6422790, marks=95, email='Sheryll Towler_Ernest Rossbach@DSA.com'),
 Row(age=28, gender='Male', name='Leontine Phillips', course='PF', roll=6442094, marks=78, email='Michelle Ruggiero_Paris Hutton@OOP.com'),